/**
 * Tests for the per-feature ⓘ explainers (feedback F15).
 *
 * Two jobs:
 *  1. the popover behaves (opens, closes on Escape/close button, labelled);
 *  2. the COPY obeys its editorial rules — short, name-free (Jose's ruling
 *     2026-08-09: no contact identities outside the disclaimer surfaces), and
 *     not a restatement of the four signed-off watermark constants.
 */
import { render, screen, fireEvent } from '@testing-library/react'
import { describe, it, expect, vi } from 'vitest'
import { InfoPopover } from '../InfoPopover'
import { INFO_TOPICS } from '../infoCopy'
import { GUARDRAIL_CONTACTS } from '../../guardrails/contacts'

const TOPIC_KEYS = ['chat', 'dashboard', 'filters', 'exports'] as const

describe('info copy', () => {
  it('covers every major feature area', () => {
    for (const key of TOPIC_KEYS) expect(INFO_TOPICS[key]).toBeDefined()
  })

  it('is short — two to four sentences per topic', () => {
    for (const key of TOPIC_KEYS) {
      const topic = INFO_TOPICS[key]
      expect(topic.body.length).toBeGreaterThanOrEqual(2)
      expect(topic.body.length).toBeLessThanOrEqual(4)
      const sentences = topic.body.join(' ').split(/[.!?](\s|$)/).filter((s) => s.trim())
      expect(sentences.length).toBeLessThanOrEqual(8)
    }
  })

  it('carries no contact names or email addresses', () => {
    const all = TOPIC_KEYS.map((k) => `${INFO_TOPICS[k].title} ${INFO_TOPICS[k].body.join(' ')}`).join(' ')
    for (const contact of GUARDRAIL_CONTACTS) {
      expect(all).not.toContain(contact.name)
      expect(all).not.toContain(contact.email)
    }
    expect(all).not.toMatch(/[\w.+-]+@[A-Za-z][\w-]*\.[A-Za-z]{2,}/)
    expect(all).not.toMatch(/mailto:/)
  })

  it('does not restate the signed-off watermark / SOP legal wording', () => {
    const all = TOPIC_KEYS.map((k) => INFO_TOPICS[k].body.join(' ')).join(' ')
    // Verbatim fragments of WATERMARK_BANNER / PROVENANCE_NOTICE /
    // SOP_DISCLOSURE / PRODUCT_FOOTER must not be duplicated here.
    for (const fragment of [
      'AI V0 DRAFT',
      'REQUIRES HUMAN VALIDATION',
      'requires human quality assurance before use or citation',
      'CGIAR uses AI-assisted tools within its reporting workflows',
      'reviewed, validated, and approved by responsible human authors',
      'Generated by the CGIAR Innovation Analytics Platform',
    ]) {
      expect(all).not.toContain(fragment)
    }
  })

  it('keeps the shipped register — result codes, method, cross-check', () => {
    expect(INFO_TOPICS.chat.body.join(' ')).toMatch(/result codes/)
    expect(INFO_TOPICS.chat.body.join(' ')).toMatch(/counting method/)
    expect(INFO_TOPICS.dashboard.body.join(' ')).toMatch(/Results Dashboard/)
    expect(INFO_TOPICS.exports.body.join(' ')).toMatch(/watermark/)
  })
})

describe('InfoPopover', () => {
  it('is closed by default and labelled for screen readers', () => {
    render(<InfoPopover topic={INFO_TOPICS.chat} />)
    const btn = screen.getByTestId('info-button-chat')
    expect(btn).toHaveAttribute('aria-label', 'About Chat')
    expect(btn).toHaveAttribute('aria-expanded', 'false')
    expect(screen.queryByTestId('info-panel-chat')).toBeNull()
  })

  it('opens on click and renders every paragraph in a dialog', () => {
    render(<InfoPopover topic={INFO_TOPICS.filters} />)
    fireEvent.click(screen.getByTestId('info-button-filters'))

    const panel = screen.getByTestId('info-panel-filters')
    expect(panel).toHaveAttribute('role', 'dialog')
    expect(panel).toHaveAttribute('aria-label', 'Data scope')
    for (const para of INFO_TOPICS.filters.body) {
      expect(panel.textContent).toContain(para)
    }
  })

  it('closes on Escape', () => {
    render(<InfoPopover topic={INFO_TOPICS.dashboard} />)
    fireEvent.click(screen.getByTestId('info-button-dashboard'))
    expect(screen.getByTestId('info-panel-dashboard')).toBeTruthy()

    fireEvent.keyDown(document, { key: 'Escape' })
    expect(screen.queryByTestId('info-panel-dashboard')).toBeNull()
  })

  it('closes via the close button and returns focus to the trigger', () => {
    render(<InfoPopover topic={INFO_TOPICS.exports} />)
    const btn = screen.getByTestId('info-button-exports')
    fireEvent.click(btn)
    fireEvent.click(screen.getByLabelText('Close the Exports explainer'))
    expect(screen.queryByTestId('info-panel-exports')).toBeNull()
    expect(document.activeElement).toBe(btn)
  })

  it('closes on an outside click', () => {
    render(
      <div>
        <span data-testid="outside">elsewhere</span>
        <InfoPopover topic={INFO_TOPICS.chat} />
      </div>,
    )
    fireEvent.click(screen.getByTestId('info-button-chat'))
    expect(screen.getByTestId('info-panel-chat')).toBeTruthy()
    fireEvent.mouseDown(screen.getByTestId('outside'))
    expect(screen.queryByTestId('info-panel-chat')).toBeNull()
  })

  it('is a passive explainer, not a modal', () => {
    // aria-modal would tell assistive tech the rest of the surface is inert;
    // these popovers must never block the feature they explain.
    render(<InfoPopover topic={INFO_TOPICS.chat} />)
    fireEvent.click(screen.getByTestId('info-button-chat'))
    expect(screen.getByTestId('info-panel-chat')).not.toHaveAttribute('aria-modal')
  })

  it('renders every topic without crashing', () => {
    for (const key of TOPIC_KEYS) {
      const { unmount } = render(<InfoPopover topic={INFO_TOPICS[key]} />)
      fireEvent.click(screen.getByTestId(`info-button-${INFO_TOPICS[key].id}`))
      expect(screen.getByTestId(`info-panel-${INFO_TOPICS[key].id}`)).toBeTruthy()
      unmount()
    }
    expect(vi.isMockFunction(vi.fn())).toBe(true)
  })
})
