"""
Shared AI-content watermark / disclaimer utility for every export format.

Every artefact the tool produces (DOCX, PDF, HTML, HTML-dashboard, Markdown)
must carry a standardized, machine-and-human-readable notice that the content
is AI-assisted and requires human quality assurance before use or citation.
This is a hard requirement of Julien Colomer's standing CGIAR AI-disclaimer
policy (see the July 7, 2026 anchor call and the CGIAR SO SOP on AI Tools
Management, effective 1-Jan-2026).

The verbatim source strings were recovered from three donors and consolidated
here (see the July-7 build brief, Addendum §4):

1. Marc Schut's spoken spec for document marks (July 7 call, ~06:34): a
   standardized box "on top" saying the output is based on CGIAR innovation
   data plus AI interpretation, with a human-QA requirement.
2. Julien Colomer's "Scaffolding, not substitute" deck (27-02-26): the V0/V1
   authorship framework and the standard disclosure sentence.
3. The Zero-Draft Reports export code (`docxGenerator.js`): the
   ``AI V0 DRAFT - REQUIRES HUMAN VALIDATION`` watermark string, adapted here
   for the Innovation Analytics product name.
4. The CGIAR SO SOP on AI Tools Management: the mandatory guidance line.

This module is deliberately dependency-free at import time (python-docx is
imported lazily inside the DOCX helper) so it can be imported from any
exporter without adding a hard dependency.
"""

from __future__ import annotations

from datetime import datetime

# ---------------------------------------------------------------------------
# Canonical wording — the single source of truth for all export formats.
# Edit these constants (Jose drafts final, Marc sanity-checks) and every
# export surface updates in lockstep.
# ---------------------------------------------------------------------------

#: Short, bold banner shown at the very top of every exported artefact.
#: Adapted from the Zero-Draft Reports V0-draft string for this product.
WATERMARK_BANNER: str = "AI V0 DRAFT — REQUIRES HUMAN VALIDATION"

#: The composite provenance / QA notice (Addendum §4 "Suggested composite copy").
#: ``{date}`` is substituted with the export date.
PROVENANCE_NOTICE: str = (
    "Based on CGIAR innovation data (PRMS); includes AI-added interpretation; "
    "requires human quality assurance before use or citation. "
    "Data as of {date}."
)

#: The CGIAR SO SOP mandatory disclosure sentence (Julien Colomer's deck).
SOP_DISCLOSURE: str = (
    "CGIAR uses AI-assisted tools within its reporting workflows to support "
    "evidence synthesis and draft preparation. All published content is "
    "reviewed, validated, and approved by responsible human authors prior to "
    "release."
)

#: Footer run identifying the generating product (adapted from the zero-draft
#: ``Zero Draft • Generated from CGIAR Zero Draft Report Assistant • …`` string).
PRODUCT_FOOTER: str = "Generated by the CGIAR Innovation Analytics Platform"

#: Bold-red colour used for the watermark banner in DOCX (matches the donor's
#: ``B40000``).
_WATERMARK_RGB: tuple[int, int, int] = (0xB4, 0x00, 0x00)


def watermark_date(date: datetime | None = None) -> str:
    """Return the human-readable date string used in the provenance notice."""
    return (date or datetime.now()).strftime("%Y-%m-%d")


def provenance_notice(date: datetime | None = None) -> str:
    """Return the provenance notice with the date substituted in."""
    return PROVENANCE_NOTICE.format(date=watermark_date(date))


# ---------------------------------------------------------------------------
# Plain-text / Markdown
# ---------------------------------------------------------------------------

def watermark_markdown(date: datetime | None = None) -> str:
    """Return a Markdown block containing the full AI-content notice.

    Rendered as a blockquote so it stands out at the top of the document and
    survives conversion to other formats.
    """
    return (
        f"> **{WATERMARK_BANNER}**\n>\n"
        f"> {provenance_notice(date)}\n>\n"
        f"> {SOP_DISCLOSURE}\n"
    )


def watermark_plain(date: datetime | None = None) -> str:
    """Return a single-line plain-text notice (for logs / minimal contexts)."""
    return f"{WATERMARK_BANNER} — {provenance_notice(date)} {SOP_DISCLOSURE}"


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

#: Inline CSS for the HTML watermark box. Kept self-contained so exported HTML
#: files render correctly with no external stylesheet.
WATERMARK_HTML_CSS: str = (
    ".ai-watermark{border:2px solid #b40000;background:#fff5f5;color:#5a0000;"
    "border-radius:8px;padding:0.75rem 1rem;margin:0 0 1.25rem;font-size:0.85rem;"
    "line-height:1.45;}"
    ".ai-watermark .ai-watermark-banner{font-weight:700;color:#b40000;"
    "letter-spacing:0.02em;text-transform:uppercase;display:block;margin-bottom:0.35rem;}"
    ".ai-watermark .ai-watermark-sop{color:#7a4a4a;font-style:italic;margin-top:0.35rem;display:block;}"
)


def watermark_html(date: datetime | None = None) -> str:
    """Return an HTML ``<div class="ai-watermark">`` block with the full notice.

    Callers are responsible for including :data:`WATERMARK_HTML_CSS` in the
    document ``<style>`` (or a stylesheet). :func:`watermark_html_style` returns
    a ready-to-embed ``<style>`` tag for standalone documents.
    """
    return (
        '<div class="ai-watermark" role="note" aria-label="AI-generated content notice">'
        f'<span class="ai-watermark-banner">{WATERMARK_BANNER}</span>'
        f"{provenance_notice(date)}"
        f'<span class="ai-watermark-sop">{SOP_DISCLOSURE}</span>'
        "</div>"
    )


def watermark_html_style() -> str:
    """Return a ``<style>`` tag carrying the watermark CSS (for standalone HTML)."""
    return f"<style>{WATERMARK_HTML_CSS}</style>"


# ---------------------------------------------------------------------------
# DOCX (python-docx)
# ---------------------------------------------------------------------------

def apply_ai_watermark(doc, *, date: datetime | None = None) -> None:
    """Apply the AI-content watermark to a python-docx ``Document`` in place.

    Inserts a bold-red banner paragraph, the provenance notice, and the SOP
    disclosure sentence at the *very top* of the document body, and adds the
    banner + provenance line to the page footer so it appears on every page.

    Args:
        doc:  A ``docx.Document`` instance.
        date: Export date; defaults to now.

    This is a no-op-safe helper: any failure to style the footer is swallowed
    (the top-of-document banner is the load-bearing part and always succeeds).
    """
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    banner_color = RGBColor(*_WATERMARK_RGB)

    # --- Top-of-document watermark box (inserted before the current first para) ---
    body = doc.element.body
    # Build the three notice paragraphs, then move them to the top in order.
    banner_para = doc.add_paragraph()
    banner_run = banner_para.add_run(WATERMARK_BANNER)
    banner_run.bold = True
    banner_run.font.size = Pt(11)
    banner_run.font.color.rgb = banner_color

    prov_para = doc.add_paragraph()
    prov_run = prov_para.add_run(provenance_notice(date))
    prov_run.font.size = Pt(9)
    prov_run.font.color.rgb = RGBColor(0x5A, 0x00, 0x00)

    sop_para = doc.add_paragraph()
    sop_run = sop_para.add_run(SOP_DISCLOSURE)
    sop_run.font.size = Pt(8)
    sop_run.italic = True
    sop_run.font.color.rgb = RGBColor(0x7A, 0x4A, 0x4A)

    # Move the three paragraphs to the very top of the body, preserving order.
    for para in (sop_para, prov_para, banner_para):
        body.insert(0, para._p)

    # --- Footer on every page ---
    try:
        section = doc.sections[0]
        footer = section.footer
        fpara = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        fpara.alignment = WD_ALIGN_PARAGRAPH.LEFT
        frun = fpara.add_run(f"{PRODUCT_FOOTER} • {WATERMARK_BANNER} • {provenance_notice(date)}")
        frun.font.size = Pt(8)
        frun.font.color.rgb = banner_color
    except Exception:  # pragma: no cover - footer styling is best-effort
        pass
