"""
Shared AI-content watermark / disclaimer utility for every export format.

Every artefact the tool produces (DOCX, PDF, HTML, HTML-dashboard, Markdown)
must carry a standardized, machine-and-human-readable notice that the content
is AI-assisted and requires human quality assurance before use or citation.
This is a hard requirement of Julien Colomer's standing CGIAR AI-disclaimer
policy (see the July 7, 2026 anchor call and the CGIAR SO SOP on AI Tools
Management, effective 1-Jan-2026).

The verbatim source strings were recovered from three donors and consolidated
here (see the July-7 build brief, Addendum §4):

1. Marc Schut's spoken spec for document marks (July 7 call, ~06:34): a
   standardized box "on top" saying the output is based on CGIAR innovation
   data plus AI interpretation, with a human-QA requirement.
2. Julien Colomer's "Scaffolding, not substitute" deck (27-02-26): the V0/V1
   authorship framework and the standard disclosure sentence.
3. The Zero-Draft Reports export code (`docxGenerator.js`): the
   ``AI V0 DRAFT - REQUIRES HUMAN VALIDATION`` watermark string, adapted here
   for the Innovation Analytics product name.
4. The CGIAR SO SOP on AI Tools Management: the mandatory guidance line.

This module is deliberately dependency-free at import time (python-docx is
imported lazily inside the DOCX helper) so it can be imported from any
exporter without adding a hard dependency.
"""

from __future__ import annotations

import html as _html
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# Canonical wording — the single source of truth for all export formats.
# Edit these constants (Jose drafts final, Marc sanity-checks) and every
# export surface updates in lockstep.
# ---------------------------------------------------------------------------

#: Short, bold banner shown at the very top of every exported artefact.
#: Adapted from the Zero-Draft Reports V0-draft string for this product.
WATERMARK_BANNER: str = "AI V0 DRAFT — REQUIRES HUMAN VALIDATION"

#: The composite provenance / QA notice (Addendum §4 "Suggested composite copy").
#: ``{date}`` is substituted with the export date.
PROVENANCE_NOTICE: str = (
    "Based on CGIAR innovation data (PRMS); includes AI-added interpretation; "
    "requires human quality assurance before use or citation. "
    "Data as of {date}."
)

#: The CGIAR SO SOP mandatory disclosure sentence (Julien Colomer's deck).
SOP_DISCLOSURE: str = (
    "CGIAR uses AI-assisted tools within its reporting workflows to support "
    "evidence synthesis and draft preparation. All published content is "
    "reviewed, validated, and approved by responsible human authors prior to "
    "release."
)

#: Footer run identifying the generating product (adapted from the zero-draft
#: ``Zero Draft • Generated from CGIAR Zero Draft Report Assistant • …`` string).
PRODUCT_FOOTER: str = "Generated by the CGIAR Innovation Analytics Platform"

#: Bold-red colour used for the watermark banner in DOCX (matches the donor's
#: ``B40000``).
_WATERMARK_RGB: tuple[int, int, int] = (0xB4, 0x00, 0x00)


# ---------------------------------------------------------------------------
# NO CONTACT IDENTITIES IN EXPORTS — Jose Luis Berenguer's ruling, 2026-08-09.
#
# A previous build (commit a92b8f7) carried a "reach out if in doubt" line
# naming individual people and their email addresses into every exported
# artefact. That was reverted: exported files travel outside the app — email
# attachments, shared drives, print — and must NOT carry personal contact
# identities. The export wording is the plain "AI-generated V0 draft, requires
# human validation" pattern, matching the CGIAR AI Zero Drafts exporter, whose
# documents carry no contact line either.
#
# The contact route still exists, but ONLY on the in-app surfaces
# (`frontend/src/components/guardrails/contacts.ts` → DisclaimerModal /
# DisclaimerFooter), where it is reachable and attributable. Do not mirror
# those constants back into this module — `tests/test_watermark.py`
# (`test_exports_carry_no_contact_identities`) reads contacts.ts and asserts
# that none of its names, emails or its lead-in sentence appear in ANY export
# surface.
# ---------------------------------------------------------------------------

#: Zero-draft-pattern export timestamp line. ``{date}``/``{time}`` are filled by
#: :func:`export_timestamp_line`. Always rendered in UTC, like the donor.
EXPORT_TIMESTAMP_LINE: str = "Export generated on {date} at {time} UTC."


def watermark_date(date: datetime | None = None) -> str:
    """Return the human-readable date string used in the provenance notice."""
    return (date or datetime.now()).strftime("%Y-%m-%d")


def provenance_notice(date: datetime | None = None) -> str:
    """Return the provenance notice with the date substituted in."""
    return PROVENANCE_NOTICE.format(date=watermark_date(date))


def export_timestamp_line(date: datetime | None = None) -> str:
    """Return the "Export generated on ... UTC." line (zero-draft pattern).

    Mirrors the donor's ``Export generated on 9 August 2026 at 14:30 UTC.``
    string. When ``date`` is omitted the current UTC time is used; tests pin a
    naive datetime, which is rendered as-is (assumed already UTC).

    Args:
        date: Export timestamp; defaults to ``datetime.now(timezone.utc)``.
    """
    dt = date if date is not None else datetime.now(timezone.utc)
    # ``%-d`` is not portable, so build the non-zero-padded day by hand.
    return EXPORT_TIMESTAMP_LINE.format(
        date=f"{dt.day} {dt.strftime('%B %Y')}",
        time=dt.strftime("%H:%M"),
    )


# ---------------------------------------------------------------------------
# Plain-text / Markdown
# ---------------------------------------------------------------------------

def watermark_markdown(date: datetime | None = None) -> str:
    """Return a Markdown block containing the full AI-content notice.

    Rendered as a blockquote so it stands out at the top of the document and
    survives conversion to other formats.
    """
    return (
        f"> **{WATERMARK_BANNER}**\n>\n"
        f"> {provenance_notice(date)}\n>\n"
        f"> {export_timestamp_line(date)}\n>\n"
        f"> {SOP_DISCLOSURE}\n"
    )


def watermark_markdown_footer(date: datetime | None = None) -> str:
    """Return the end-of-document Markdown footer.

    Markdown has no pages, so the per-page footer the DOCX/PDF surfaces carry
    is approximated by a single footer at the very END of the document — the
    last thing a reader (or a copy-paste) sees.
    """
    return (
        f"\n---\n*{PRODUCT_FOOTER} • {WATERMARK_BANNER} • {provenance_notice(date)}*\n"
    )


def watermark_plain(date: datetime | None = None) -> str:
    """Return a single-line plain-text notice (for logs / minimal contexts)."""
    return f"{WATERMARK_BANNER} — {provenance_notice(date)} {SOP_DISCLOSURE}"


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

#: Inline CSS for the HTML watermark box. Kept self-contained so exported HTML
#: files render correctly with no external stylesheet.
WATERMARK_HTML_CSS: str = (
    ".ai-watermark{border:2px solid #b40000;background:#fff5f5;color:#5a0000;"
    "border-radius:8px;padding:0.75rem 1rem;margin:0 0 1.25rem;font-size:0.85rem;"
    "line-height:1.45;}"
    ".ai-watermark .ai-watermark-banner{font-weight:700;color:#b40000;"
    "letter-spacing:0.02em;text-transform:uppercase;display:block;margin-bottom:0.35rem;}"
    ".ai-watermark .ai-watermark-sop{color:#7a4a4a;font-style:italic;margin-top:0.35rem;display:block;}"
    ".ai-watermark .ai-watermark-timestamp{color:#7a4a4a;display:block;margin-top:0.35rem;}"
    # --- Diagonal per-page draft watermark (zero-draft parity) --------------
    # Chromium repeats ``position:fixed`` elements on every printed page, which
    # is what turns this single div into the donor's per-page diagonal mark in
    # the PDF as well as on screen.
    #
    # Two things here were established by headless-Chrome print renders, not by
    # reading specs — change them only with a render to back it up:
    #
    # 1. The overlay is a full-page fixed *container* centring a rotated inner
    #    span, NOT a rotated element offset with top/left:50%. The latter is
    #    laid out against the whole document rather than the page box, so it
    #    appears once and clipped instead of repeating per page.
    # 2. The mark sits ON TOP of the content (high z-index), not behind it.
    #    IA's exports are built from opaque message cards (.message, .tool,
    #    .thinking all carry solid backgrounds); a behind-content watermark is
    #    painted over by them and survives only in the page margins. Layering it
    #    on top also matches the donor, whose pdfGenerator.js draws the logo as
    #    the bottom layer but the draft TEXT watermark as the top layer.
    #    ``pointer-events:none`` + ``user-select:none`` keep it inert, and .08
    #    opacity keeps the text underneath fully legible.
    ".ai-watermark-overlay{position:fixed;top:0;left:0;width:100%;height:100%;"
    "display:flex;align-items:center;justify-content:center;overflow:hidden;"
    "pointer-events:none;user-select:none;-webkit-user-select:none;z-index:9998;}"
    # 2.75rem keeps the 39-character banner inside the page diagonal; larger
    # sizes are clipped by the page edges.
    ".ai-watermark-overlay span{transform:rotate(-45deg);transform-origin:center center;"
    "font-size:2.75rem;font-weight:700;letter-spacing:0.04em;text-align:center;"
    "white-space:nowrap;color:#b40000;opacity:.08;}"
    # --- Print-only per-page footer (zero-draft parity) ---------------------
    ".ai-watermark-pagefooter{display:none;}"
    "@media print{"
    # z-index above the overlay: the running footer is furniture that must stay
    # readable, and opaque content blocks would otherwise paint over it.
    ".ai-watermark-pagefooter{display:block;position:fixed;bottom:0;left:0;right:0;"
    "z-index:9999;font-size:0.65rem;color:#666;text-align:center;padding:2px 0;"
    "border-top:1px solid #ddd;background:#fff;}"
    ".ai-watermark-pagefooter .ai-watermark-banner{color:#b40000;font-weight:700;}"
    ".ai-watermark-overlay span{opacity:.10;}"
    "}"
)


def watermark_html_overlay(date: datetime | None = None) -> str:
    """Return the per-page HTML/PDF watermark furniture.

    Two ``position:fixed`` elements, to be emitted immediately after ``<body>``:

    1. ``.ai-watermark-overlay`` — the diagonal red draft mark, layered over the
       content at low opacity and made inert with ``pointer-events:none`` (see
       :data:`WATERMARK_HTML_CSS` for why it is not behind the content).
    2. ``.ai-watermark-pagefooter`` — a print-only bottom footer carrying the
       product line, banner and provenance notice.

    Both repeat on every page when the document is printed to PDF (the product
    renders PDFs by driving headless Chromium over the HTML export, so this one
    helper delivers HTML *and* PDF parity).
    """
    return (
        f'<div class="ai-watermark-overlay" aria-hidden="true">'
        f"<span>{WATERMARK_BANNER}</span></div>"
        f'<div class="ai-watermark-pagefooter" aria-hidden="true">'
        f"{PRODUCT_FOOTER} • "
        f'<span class="ai-watermark-banner">{WATERMARK_BANNER}</span> • '
        f"{provenance_notice(date)}"
        f"</div>"
    )


def watermark_html(date: datetime | None = None) -> str:
    """Return an HTML ``<div class="ai-watermark">`` block with the full notice.

    Callers are responsible for including :data:`WATERMARK_HTML_CSS` in the
    document ``<style>`` (or a stylesheet). :func:`watermark_html_style` returns
    a ready-to-embed ``<style>`` tag for standalone documents.
    """
    return (
        '<div class="ai-watermark" role="note" aria-label="AI-generated content notice">'
        f'<span class="ai-watermark-banner">{WATERMARK_BANNER}</span>'
        f"{provenance_notice(date)}"
        f'<span class="ai-watermark-timestamp">{export_timestamp_line(date)}</span>'
        f'<span class="ai-watermark-sop">{SOP_DISCLOSURE}</span>'
        "</div>"
    )


def watermark_html_style() -> str:
    """Return a ``<style>`` tag carrying the watermark CSS (for standalone HTML)."""
    return f"<style>{WATERMARK_HTML_CSS}</style>"


# ---------------------------------------------------------------------------
# DOCX (python-docx)
# ---------------------------------------------------------------------------

#: Namespace declarations needed for the raw VML watermark shape. python-docx's
#: ``nsdecls`` helper only knows the WordprocessingML namespaces, so the VML /
#: Office / Word-drawing ones are spelled out here.
_VML_NSDECLS = (
    'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" '
    'xmlns:v="urn:schemas-microsoft-com:vml" '
    'xmlns:o="urn:schemas-microsoft-com:office:office" '
    'xmlns:w10="urn:schemas-microsoft-com:office:word"'
)

#: The standard Word "text on a path" shape definition (``_x0000_t136``). Word
#: emits this verbatim alongside every text watermark; LibreOffice needs it too.
_VML_SHAPETYPE = (
    '<v:shapetype id="_x0000_t136" coordsize="21600,21600" o:spt="136" adj="10800"'
    ' path="m@7,l@8,m@5,21600l@6,21600e">'
    "<v:formulas>"
    '<v:f eqn="sum #0 0 10800"/><v:f eqn="prod #0 2 1"/><v:f eqn="sum 21600 0 @1"/>'
    '<v:f eqn="sum 0 0 @2"/><v:f eqn="sum 21600 0 @3"/><v:f eqn="if @0 @3 0"/>'
    '<v:f eqn="if @0 21600 @1"/><v:f eqn="if @0 0 @2"/><v:f eqn="if @0 @4 21600"/>'
    '<v:f eqn="mid @5 @6"/><v:f eqn="mid @8 @5"/><v:f eqn="mid @7 @8"/>'
    '<v:f eqn="mid @6 @7"/><v:f eqn="sum @6 0 @5"/>'
    "</v:formulas>"
    '<v:path textpathok="t" o:connecttype="custom"'
    ' o:connectlocs="@9,0;@10,10800;@11,21600;@12,10800"'
    ' o:connectangles="270,180,90,0"/>'
    '<v:textpath on="t" fitshape="t"/>'
    '<v:handles><v:h position="#0,bottomRight" xrange="6629,14971"/></v:handles>'
    '<o:lock v:ext="edit" text="t" shapetype="t"/>'
    "</v:shapetype>"
)


def _vml_watermark_xml(text: str) -> str:
    """Build the raw ``<w:p>`` XML carrying the diagonal VML text watermark.

    This is the classic Word watermark: a ``PowerPlusWaterMarkObject`` text-path
    shape anchored to the page margins, rotated 315°, filled bold-red at low
    opacity and pushed behind the text layer with a negative ``z-index``. It
    lives in the section *header*, which is what makes it repeat on every page.

    A raw-XML build is required because python-docx has no drawing API; the
    element is parsed with python-docx's own oxml parser so it round-trips
    through ``Document.save()`` unchanged.
    """
    safe = _html.escape(text, quote=True)
    style = (
        "position:absolute;margin-left:0;margin-top:0;"
        "width:527.85pt;height:105.5pt;rotation:315;z-index:-251654144;"
        "mso-position-horizontal:center;mso-position-horizontal-relative:margin;"
        "mso-position-vertical:center;mso-position-vertical-relative:margin"
    )
    return (
        f"<w:p {_VML_NSDECLS}><w:r><w:pict>"
        f"{_VML_SHAPETYPE}"
        f'<v:shape id="PowerPlusWaterMarkObject1" o:spid="_x0000_s2049"'
        f' type="#_x0000_t136" style="{style}"'
        f' o:allowincell="f" fillcolor="#b40000" stroked="f">'
        f'<v:fill opacity=".13"/>'
        f'<v:textpath style="font-family:&quot;Calibri&quot;;font-size:1pt"'
        f' string="{safe}"/>'
        f'<w10:wrap anchorx="margin" anchory="margin"/>'
        f"</v:shape>"
        f"</w:pict></w:r></w:p>"
    )


def _notice_box_pr_xml() -> str:
    """Build the ``<w:pPr>`` fragment that boxes and shades a notice paragraph.

    All four edges are declared on EVERY notice paragraph, deliberately. Word
    and LibreOffice merge borders across consecutive paragraphs only when the
    border definitions are *byte-identical*, collapsing them into a single box
    and suppressing the interior horizontal rules. The intuitive alternative —
    top edge on the first paragraph, bottom on the last — makes the paragraphs
    non-identical, which defeats the merge and renders the vertical edges as
    disconnected per-paragraph segments (verified in a LibreOffice render).

    The result is the zero-draft "Data Notice" *structure* in Innovation
    Analytics' own palette (``B40000`` on ``FFF5F5``, matching the HTML
    ``.ai-watermark`` box).
    """
    edge = '<w:{side} w:val="single" w:sz="6" w:space="4" w:color="B40000"/>'
    borders = "".join(
        edge.format(side=side) for side in ("top", "left", "bottom", "right")
    )
    return (
        f"<w:pBdr>{borders}</w:pBdr>"
        f'<w:shd w:val="clear" w:color="auto" w:fill="FFF5F5"/>'
        f'<w:ind w:left="144" w:right="144"/>'
    )


#: Schema order of ``<w:pPr>`` children (ECMA-376 §17.3.1.26). ``w:pBdr`` and
#: ``w:shd`` have no python-docx accessor, so elements built here must be
#: inserted at the right index by hand — Word rejects out-of-order ``pPr``.
_PPR_TAG_SEQ = (
    "w:pStyle", "w:keepNext", "w:keepLines", "w:pageBreakBefore", "w:framePr",
    "w:widowControl", "w:numPr", "w:suppressLineNumbers", "w:pBdr", "w:shd",
    "w:tabs", "w:suppressAutoHyphens", "w:kinsoku", "w:wordWrap",
    "w:overflowPunct", "w:topLinePunct", "w:autoSpaceDE", "w:autoSpaceDN",
    "w:bidi", "w:adjustRightInd", "w:snapToGrid", "w:spacing", "w:ind",
    "w:contextualSpacing", "w:mirrorIndents", "w:suppressOverlap", "w:jc",
    "w:textDirection", "w:textAlignment", "w:textboxTightWrap", "w:outlineLvl",
    "w:divId", "w:cnfStyle", "w:rPr", "w:sectPr", "w:pPrChange",
)


def _insert_into_pPr(pPr, element) -> None:
    """Insert ``element`` into ``pPr`` at its schema-mandated position.

    Order-independent: safe to call before or after python-docx has added its
    own ``w:jc`` / ``w:tabs`` children.
    """
    from docx.oxml.ns import qn

    index = {qn(tag): i for i, tag in enumerate(_PPR_TAG_SEQ)}
    rank = index.get(element.tag, len(_PPR_TAG_SEQ))
    for existing in pPr:
        if index.get(existing.tag, len(_PPR_TAG_SEQ)) > rank:
            existing.addprevious(element)
            return
    pPr.append(element)


def _page_number_field_xml() -> str:
    """Build the run sequence for a right-aligned ``Page N`` field.

    Uses the explicit ``fldChar`` form (begin / instrText / separate / result /
    end) rather than ``w:fldSimple``: the former is what Word itself writes and
    is the form LibreOffice updates most reliably. The cached result run is
    ``1`` so the field shows something even in viewers that never recalculate.
    """
    rpr = '<w:rPr><w:sz w:val="16"/><w:color w:val="666666"/></w:rPr>'
    return (
        f"<w:r {_VML_NSDECLS}>{rpr}<w:tab/><w:t xml:space=\"preserve\">Page </w:t></w:r>"
        f"<w:r {_VML_NSDECLS}>{rpr}<w:fldChar w:fldCharType=\"begin\"/></w:r>"
        f"<w:r {_VML_NSDECLS}>{rpr}<w:instrText xml:space=\"preserve\"> PAGE </w:instrText></w:r>"
        f"<w:r {_VML_NSDECLS}>{rpr}<w:fldChar w:fldCharType=\"separate\"/></w:r>"
        f"<w:r {_VML_NSDECLS}>{rpr}<w:t>1</w:t></w:r>"
        f"<w:r {_VML_NSDECLS}>{rpr}<w:fldChar w:fldCharType=\"end\"/></w:r>"
    )


def apply_ai_watermark(doc, *, date: datetime | None = None, title: str | None = None) -> None:
    """Apply the AI-content watermark to a python-docx ``Document`` in place.

    Produces the same set of marks the CGIAR Zero-Draft Reports exporter puts on
    its documents, in Innovation Analytics' own palette and wording:

    * a bordered, shaded **notice box** at the very top of the body — banner,
      provenance notice + export timestamp, SOP disclosure (three paragraphs;
      no contact line — see Jose's 2026-08-09 ruling above);
    * a diagonal red **draft watermark on every page** (VML text shape in the
      section header, behind the content);
    * a per-page **header**: document title + bold-red banner, thin rule under;
    * the existing per-page **footer**, plus a right-aligned ``Page N`` field.

    Args:
        doc:   A ``docx.Document`` instance.
        date:  Export date; defaults to now.
        title: Document title for the running header. Falls back to
               :data:`PRODUCT_FOOTER` when omitted.

    This is a no-op-safe helper: any failure in the header, footer or VML
    watermark is swallowed (the top-of-document notice box is the load-bearing
    part and always succeeds).
    """
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_TAB_ALIGNMENT
    from docx.oxml import parse_xml

    banner_color = RGBColor(*_WATERMARK_RGB)
    muted_color = RGBColor(0x7A, 0x4A, 0x4A)

    # --- Top-of-document watermark box (inserted before the current first para) ---
    body = doc.element.body
    # Build the three notice paragraphs, then move them to the top in order.
    banner_para = doc.add_paragraph()
    banner_run = banner_para.add_run(WATERMARK_BANNER)
    banner_run.bold = True
    banner_run.font.size = Pt(11)
    banner_run.font.color.rgb = banner_color

    prov_para = doc.add_paragraph()
    prov_run = prov_para.add_run(provenance_notice(date))
    prov_run.font.size = Pt(9)
    prov_run.font.color.rgb = RGBColor(0x5A, 0x00, 0x00)
    # Export timestamp rides in the same paragraph on its own line, exactly as
    # the zero-draft Data Notice does (a `break: 1` run after the provenance).
    ts_run = prov_para.add_run()
    ts_run.add_break()
    ts_run.add_text(export_timestamp_line(date))
    ts_run.font.size = Pt(9)
    ts_run.font.color.rgb = RGBColor(0x5A, 0x00, 0x00)

    sop_para = doc.add_paragraph()
    sop_run = sop_para.add_run(SOP_DISCLOSURE)
    sop_run.font.size = Pt(8)
    sop_run.italic = True
    sop_run.font.color.rgb = muted_color

    # Box + shade the three notice paragraphs so they read as one panel.
    notice_paras = (banner_para, prov_para, sop_para)
    for para in notice_paras:
        try:
            # Tight spacing keeps the merged box compact rather than leaving
            # gaps where the paragraph spacing would break the shading.
            para.paragraph_format.space_after = Pt(4)
            para.paragraph_format.space_before = Pt(4)
            frag = parse_xml(f"<w:pPr {_VML_NSDECLS}>{_notice_box_pr_xml()}</w:pPr>")
            pPr = para._p.get_or_add_pPr()
            for child in list(frag):
                _insert_into_pPr(pPr, child)
        except Exception:  # pragma: no cover - box styling is best-effort
            pass

    # Move the notice paragraphs to the very top of the body, preserving order.
    for para in reversed(notice_paras):
        body.insert(0, para._p)

    # --- Per-page header: title + banner, with the diagonal VML watermark ---
    try:
        section = doc.sections[0]
        header = section.header
        header.is_linked_to_previous = False
        hpara = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
        hpara.alignment = WD_ALIGN_PARAGRAPH.LEFT
        title_run = hpara.add_run(f"{title or PRODUCT_FOOTER} • ")
        title_run.font.size = Pt(9)
        title_run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
        hbanner = hpara.add_run(WATERMARK_BANNER)
        hbanner.bold = True
        hbanner.font.size = Pt(9)
        hbanner.font.color.rgb = banner_color
        # Thin rule under the running header.
        try:
            _insert_into_pPr(
                hpara._p.get_or_add_pPr(),
                parse_xml(
                    f'<w:pBdr {_VML_NSDECLS}>'
                    f'<w:bottom w:val="single" w:sz="4" w:space="4" w:color="CCCCCC"/>'
                    f"</w:pBdr>"
                ),
            )
        except Exception:  # pragma: no cover
            pass
        # The diagonal draft watermark lives in the same header part; putting it
        # first keeps it in the background layer under the running-header text.
        try:
            header._element.insert(0, parse_xml(_vml_watermark_xml(WATERMARK_BANNER)))
        except Exception:  # pragma: no cover - watermark shape is best-effort
            pass
    except Exception:  # pragma: no cover - header styling is best-effort
        pass

    # --- Footer on every page ---
    try:
        section = doc.sections[0]
        footer = section.footer
        footer.is_linked_to_previous = False
        fpara = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        fpara.alignment = WD_ALIGN_PARAGRAPH.LEFT
        frun = fpara.add_run(f"{PRODUCT_FOOTER} • {WATERMARK_BANNER} • {provenance_notice(date)}")
        frun.font.size = Pt(8)
        frun.font.color.rgb = banner_color
        # Right-aligned `Page N` field after the footer text (zero-draft layout).
        try:
            fpara.paragraph_format.tab_stops.add_tab_stop(
                Inches(6.5), WD_TAB_ALIGNMENT.RIGHT
            )
            for run_el in list(parse_xml(
                f"<w:p {_VML_NSDECLS}>{_page_number_field_xml()}</w:p>"
            )):
                fpara._p.append(run_el)
        except Exception:  # pragma: no cover - page field is best-effort
            pass
    except Exception:  # pragma: no cover - footer styling is best-effort
        pass
